watch_stylesheet: true
watch_config: true
debug: true
bars:
  main-bar:
    screens: ["*"]
    class_name: "main-bar"
    alignment:
      position: "bottom"
      align: "left"
    window_flags:
      always_on_top: true
      windows_app_bar: true
    padding:
      right: 3
      left: 3
    dimensions:
      height: 20
    padding:
      top: -20
    widgets:
      left: ["glazewm_workspaces"]
      right: ["group", "clock"]
  background-bar:
    class_name: "background-bar"
    screens: ["*"]
    alignment:
      position: "bottom"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      height: 10
    padding:
      top: -2
widgets:
  windows:
    type: "yasb.custom.CustomWidget"
    options:
      label: "🪟"
      label_alt: ""
      class_name: "windows"
      callbacks:
        on_left: 'exec cmd /c start "" /b %USERPROFILE%\dotfiles\config\windows\twm-utils\toggle-taskbar.bat'
  reload:
    type: "yasb.custom.CustomWidget"
    options:
      label: "♻️"
      label_alt: ""
      class_name: "reload"
      callbacks:
        on_left: 'exec cmd /c start "" /b glazewm.exe command wm-reload-config && yasbc.exe reload'
  group:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "group"
      widgets: [
        "bluetooth",
        "glazewm_tiling_direction",
        "weather",
        "home",
        "microphone",
        "volume",
        "wifi",
        "power_plan",
        "reload",
        "windows",
        "systray"
      ]
      collapse_options:
        enabled: true
        expanded_label: "📖"
        collapsed_label: "📕"
        label_position: "right"
        exclude_widgets: ["bluetooth", "glazewm_tiling_direction"]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
        class_name: "systray"
        label_position: "left"
        show_battery: true
        show_unpinned_button: false
        icon_size: 14
  power_plan:
    type: "yasb.power_plan.PowerPlanWidget"
    options:
      label: "🚂"
      label_alt: "<span>\uf0e7</span> Power Plan {active_plan}"
      update_interval: 5000
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "🎙️"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "⏩"
      vertical_label: "⏬"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      enable_scroll_switching: false
      app_icons:
        enabled_populated: true
        enabled_active: true
        size: 12
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "⚙️"
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      alignment: "left"
      direction: "down"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      class_name: "weather"
      label: "<span>{icon}</span>"
      label_alt: "{temp}, Rain {daily_chance_of_rain}"
      api_key: "5337407e8f054898880132623252111" # https://www.weatherapi.com/
      show_alerts: true
      tooltip: false
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "Lausanne Switzerland"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "☀️"
        clearNight: "🌙"
        cloudyDay: "☁️"
        cloudyNight: "☁️"
        rainyDay: "☔"
        rainyNight: "☔"
        snowyDay: "❄️"
        snowyNight: "❄️"
        blizzardDay: "⛄"
        blizzardNight: "⛄"
        foggyDay: "🌫️"
        foggyNight: "🌫️"
        thunderstormDay: "⛈️"
        thunderstormNight: "⛈️"
        default: "\uebaa"
      weather_card:
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "🛜"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "󰀂"
      get_exact_wifi_strength: false
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      class_name: "bluetooth"
      label: "<span>{icon}</span>"
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:bluetooth"
      icons:
        bluetooth_on: ""
        bluetooth_off: "🔴"
        bluetooth_connected: "🟢"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      class_name: "clock"
      tooltip: false
      label: "⌚{%H:%M}"
      label_alt: "📅{%d/%m/%y⌚%H:%M:%S}"
      callbacks:
        on_right: "toggle_label"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "🔊"
      audio_menu:
        show_apps: true
        show_app_icons: true
        show_apps_expanded: true
