watch_stylesheet: true
watch_config: true
debug: true
glazewm:
  start_command: "glazewm.exe"
  stop_command: "taskkill /IM glazewm.exe /F"
  reload_command: "taskkill /IM glazewm.exe /F && glazewm.exe"
bars:
  primary-bar:
    enabled: true
    screens: ["*"] 
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 22
    widgets:
      left: ["home", "glazewm_tiling_direction", "weather", "cava"]
      center: ["glazewm_workspaces"]
      right: ["battery", "wifi", "bluetooth", "volume", "clock"]
widgets:
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      enable_scroll_switching: false
      app_icons:
        enabled_populated: true
        enabled_active: true
        size: 12
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span></span>"
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      alignment: "left"
      direction: "down"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "5337407e8f054898880132623252111" # https://www.weatherapi.com/
      show_alerts: true
      tooltip: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "Lausanne Switzerland"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      weather_card:
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      foreground: "white"
      gradient_color_1: 'white'
      gradient_color_2: 'white'
      gradient_color_3: 'white'
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network-wifi"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:bluetooth"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%d/%m %H:%M}"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      audio_menu:
        show_apps: true
        show_app_icons: true
        show_apps_expanded: true
