#!zsh

cp -rfL "${HOME}/dotfiles/windows/config/." "${USERPROFILE}"
cp -rfL "${USERPROFILE}/.config/Code" "${APPDATA}"
python3 "${HOME}/dotfiles/config/less/lesskey.py" wsl > "${USERPROFILE}/.lesskey"
