#!zsh
setopt glob_dots
DOTS="$(git rev-parse --show-toplevel)"
USERPROFILE=$(wslpath `cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r'`)
APPDATA=$(wslpath `cmd.exe /c "echo %APPDATA%" 2>/dev/null | tr -d '\r'`)

cp -rfL "${DOTS}/windows/config/." "${USERPROFILE}"
cp -rfL "${DOTS}/windows/appdata-config/." "${APPDATA}"

python3 "${DOTS}/config/less/lesskey.py" wsl > "${USERPROFILE}/.lesskey"
