#!/usr/bin/zsh
configDir="${0:h}"

# dotfiles
python3 "${configDir}/dotfiles/lesskey.py" > ~/.lesskey
ln -f "${configDir}/dotfiles/.gitconfig" "${HOME}/"
echo run \"${HOME}/.tmuxrc\" > ~/.tmux.conf
mkdir -p "${HOME}/.config/vifm"
echo source "${HOME}/.vifmrc" > "${HOME}/.config/vifm/vifmrc"

if grep -q Microsoft /proc/version; then
  appData="${HOME}/AppData/Roaming"
  shellStartup="${appData}/Microsoft/Windows/Start Menu/Programs/Startup"
  # komorebi
  echo komorebic.exe start --whkd > "${shellStartup}/start_komorebic.bat"
  ln -f "${configDir}/komorebi/komorebi.json" "${HOME}/komorebi.json"
  ln -f "${configDir}/komorebi/whkdrc" "${HOME}/.config/whkdrc"
  # VSCode
  codeDir="${appData}/Code/User"
  if [[ -d ${codeDir} ]]; then
    ln -f "${configDir}/VSCode/settings.json" "${codeDir}/settings.json"
    ln -f "${configDir}/VSCode/keybindings.json" "${codeDir}/keybindings.json"
  fi
  # JetBrains
  ln -f "${configDir}/JetBrains/.ideavimrc" "${HOME}/_ideavimrc"
  for dirPattern in 'PyCharm*' 'IdeaIC*'; do
    dir=$(find "${appData}/JetBrains" -type d -name $dirPattern|sort -n|tail -n1)
    if [[ -d ${dir} ]]; then
      mkdir -p "${dir}/keymaps"
      ln -f "${configDir}/JetBrains/keybindings.xml" "${dir}/keymaps/keybindings.xml"
    fi
done
fi
