#!/usr/bin/env bash
# Install dependencies on a linux environment

# Common packages
cd ~
sudo apt-get update -y
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y curl dirmngr apt-transport-https lsb-release ca-certificates stow cmake vifm zsh tmux fzf neovim nodejs fontconfig tig qalc p7zip-full httpie ripgrep fd-find xsel

packages=(
  'https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb'
  'https://github.com/bootandy/dust/releases/download/v0.8.3/du-dust_0.8.3_amd64.deb'
)
for package in "${packages[@]}" ; do
  TEMP_DEB="$(mktemp)" && wget -O "$TEMP_DEB" $package && sudo dpkg -i "$TEMP_DEB"
done

# Antigen
mkdir $HOME/.antigen
curl -L git.io/antigen > ~/.antigen/antigen.zsh

# Nvim packages
sh -c 'curl -fLo "${HOME}"/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim +PluginInstall +qall

# Nerd fonts
TEMP_ZIP="$(mktemp)" && wget -O "$TEMP_ZIP" 'https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip' && unzip "$TEMP_ZIP" -d $HOME/.fonts
fc-cache -fv

# Finalize
mkdir ~/.config
echo source "$HOME/.zrc">$HOME/.zshrc
cd $HOME/dotfiles
stow stowme
