#!/usr/bin/env bash
cd ~

# Common packages
apt-get update -y
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get install -y stow cmake vifm zsh tmux fzf neovim xclip nodejs fontconfig default-jdk

# Rust
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
cargo install sd ripgrep fd-find

# Kotlin
curl -s https://get.sdkman.io | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk install kotlin

# Nvim packages
nvim +PluginInstall +qall

# Nerd fonts
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/InconsolataGo.zip
unzip InconsolataGo.zip -d ~/.fonts
fc-cache -fv
