#!bash
sudo cp nix/configuration.nix /etc/nixos/configuration.nix
sudo nixos-rebuild switch

nix-channel --add https://github.com/nix-community/home-manager/archive/release-25.05.tar.gz home-manager
nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
nix-channel --update
nix-shell '<home-manager>' -A install
