#!/usr/bin/bash
function github_release() {
  local tmp=$(mktemp)
  wget -O ${tmp} "https://github.com/$1/releases/latest/download/$2"
  unzip -o ${tmp} -d "${@:3}"
}
raw_github='https://raw.githubusercontent.com'

# Common packages
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y \
  curl dirmngr apt-transport-https lsb-release ca-certificates stow cmake vifm \
  zsh tmux fzf fontconfig tig qalc httpie ripgrep fd-find xsel clang nodejs jq

# nvim
github_release neovim/neovim nvim-linux64.tar.gz "${HOME}"
sudo ln -s "${HOME}/nvim-linux64/bin/nvim" "/usr/bin/nvim"

# sd
sd_tag=`curl -s https://api.github.com/repos/chmln/sd/tags | jq -r '.[0].name'`
sd="sd-${sd_tag}-x86_64-unknown-linux-musl"
github_release chmln/sd "${sd}.tar.gz" "${HOME}/bin" --strip-components=1 "${sd}/sd"

# eza
github_release eza-community/eza "eza_x86_64-unknown-linux-musl.tar.gz" "${HOME}/bin"

# vifm devicons
wget "${raw_github}/thimc/vifm_devicons/master/favicons.vifm" -O "${HOME}/.vifm.icons"

# starship
curl -sS https://starship.rs/install.sh | sh -s -- -y --bin-dir "${HOME}"/bin

# antigen
mkdir -p "${HOME}/.antigen"
curl -L git.io/antigen > "${HOME}/.antigen/antigen.zsh"

# extract
echo '#!/usr/bin/zsh
source ~/.antigen/bundles/ohmyzsh/ohmyzsh/plugins/extract/extract.plugin.zsh
extract $1' > "${HOME}/bin/extract"
chmod +x "${HOME}/bin/extract"

if grep -q Microsoft /proc/version; then
  # win32yank
  winget.exe install --id=equalsraf.win32yank -e
  # wudo
  wget "${raw_github}/Chronial/wsl-sudo/master/wsl-sudo.py" -O "${HOME}/bin/wudo"
  chmod +x "${HOME}/bin/wudo"
fi
