#!/usr/bin/bash

shopt -s dotglob
lndir() { mkdir -p "$2" && for file in "$1/"*; do ln -f "$file" "$2/"; done }
wf() { local f=$1 && shift && mkdir -p "$(dirname $f)" && "$@" > $f; }

config="${HOME}/dotfiles/config"

wf "${HOME}/.config/nvim/init.lua" echo "dofile(\"${HOME}/.nvim.lua\")"
wf "${HOME}/.config/vifm/vifmrc" echo "source ${HOME}/.vifmrc"
wf "${HOME}/.lesskey" /usr/bin/python3 "${config}/lesskey.py"

lndir "${HOME}/dotfiles/dots" "${HOME}"

if grep -q Microsoft /proc/version; then
  appData="${HOME}/AppData/Roaming"

  # VSCode
  lndir "${config}/VSCode" "${appData}/Code/User"

  # JetBrains
  ln -f "${config}/JetBrains/.ideavimrc" "${HOME}/.ideavimrc"
  for dir in $(find "${appData}/JetBrains" -type d -name "PyCharm*" -o -name "IdeaIC*"); do
    lndir "${config}/JetBrains/keymaps" "${dir}/keymaps"
  done

  # glazewm + zebar
  lndir "${config}/windows/glazewm" "${HOME}/.glzr/glazewm"
  lndir "${config}/windows/zebar/starter" "${HOME}/.glzr/zebar/starter"

  # Firefox (should activate legacyUserProfileCustomizations)
  for dir in $(find "${appData}/Mozilla/Firefox/Profiles/" -type d -name "*release*"); do
    lndir "${config}/mozilla" "${dir}/chrome"
  done
fi
