#!zsh

mkdir -p ~/.config/home-manager
cp nix/home.nix ~/.config/home-manager/home.nix
home-manager switch

if win; then
  zsh windows/setup
fi

{
  sudo nix-env --delete-generations +5 --profile /nix/var/nix/profiles/system
  sudo nix-collect-garbage -d
} >/dev/null 2>&1 &

disown
