#!/usr/bin/env bash
export HOME=$(dirname $(dirname $(realpath $0)))
mkdir $HOME/bin $HOME/.config
echo source "$HOME/.zrc">$HOME/.zshrc

local HACK_FONT_URL='https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip'
local NVIM_URL='https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz'
local SD_URL='https://github.com/chmln/sd/releases/download/v0.7.6/sd-v0.7.6-x86_64-unknown-linux-gnu'
local VIM_PLUG_URL='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
local W32Y_URL='https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip'

# OS specific
if $(grep -q Microsoft /proc/version); then
  COMMAND="WSL -u root usermod -d $HOME qleveque && "`
         `'SETX PATH "%USERPROFILE%\bin;%USERPROFILE%\dotfiles\bin;%PATH%" && '`
         `'PAUSE'
  powershell.exe -Command "start cmd.exe -Verb runAs -ArgumentList '/C $COMMAND'"
  # Windows dotfiles
  local codeDir="$HOME/AppData/Roaming/Code/User" && mkdir -p "$codeDir"
  local v; for v in settings keybindings tasks; do
    ln "$HOME/dotfiles/stowme/.config/Code/User/$v.json" "$codeDir/$v.json"
  done
  ln "$HOME/dotfiles/stowme/.ideavimrc" "$HOME/_ideavimrc"
  # Win32yank
  TMP=$(mktemp) && wget -O $TMP $W32Y_URL && unzip $TMP win32yank.exe -d $HOME/bin && chmod +x win32yank.exe
  # Hack Nerd Font
  cmd.exe /C START ' ' $HACK_FONT_URL
else
  # Hack Nerd Font
  TMP=$(mktemp) && wget -O $TMP $HACK_FONT_URL && unzip $TMP -d $HOME/.fonts && fc-cache -fv
fi

# Common packages
sudo apt-get update -y
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y curl dirmngr apt-transport-https lsb-release ca-certificates stow cmake \
  vifm zsh tmux fzf neovim nodejs fontconfig tig qalc p7zip-full httpie ripgrep fd-find xsel clang
wget -O $HOME/bin/sd $SD_URL
# Nvim
TMP=$(mktemp) && wget -O $TMP $NVIM_URL && tar xvzf $TMP -C $HOME
sudo ln -s $HOME/nvim-linux64/bin/nvim /usr/bin/nvim
sh -c 'curl -fLo "${HOME}"/.local/share/nvim/site/autoload/plug.vim --create-dirs $VIM_PLUG_URL'
nvim +PluginInstall +qall
nvim -c 'CocInstall -sync coc-json coc-highlight coc-tsserver coc-html coc-css coc-pyright coc-clangd|q'
# Antigen
mkdir $HOME/.antigen && curl -L git.io/antigen > $HOME/.antigen/antigen.zsh

# Finalize
stow -d $HOME/dotfiles -t $HOME stowme
