general:
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  show_all_in_taskbar: true

  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'

gaps:
  inner_gap: '6px'

  outer_gap:
    top: '6px'
    right: '6px'
    bottom: '-20px'
    left: '6px'

  single_window_outer_gap:
    top: '6px'
    right: '6px'
    bottom: '-20px'
    left: '6px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#ffffff'

    corner_style:
      enabled: true
      style: 'square'

  other_windows:
    border:
      enabled: true
      color: '#000000'

    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: true
      shown_on_top: false

workspaces:
  - name: "1_any"
    display_name: "󰋜"
  - name: "2_else"
    display_name: "󰥵"
  - name: "3_web"
    display_name: "󰖟"
  - name: "4_term"
    display_name: ""
  - name: "5_send"
    display_name: "󰭹"
  - name: "6_code"
    display_name: "󰅨"
  - name: "7_gui"
    display_name: "󰇞"
  - name: "8_dash"
    display_name: "󱐋"
  - name: "9_back"
    display_name: "󰀿"
  - name: "10_music"
    display_name: "󰝚"
  - name: "11_post"
    display_name: "󰇮"
  - name: "12_rest"
    display_name: "󰅶"
  - name: "13_fullscreen"
    display_name: "󰊓"

window_rules:
  - commands: ['ignore']
    match:
      - window_title: { equals: 'Appel vocal ‎- WhatsApp' }

  - commands: ['move --workspace 10_music']
    match:
      - window_process: { equals: 'Spotify' }
  - commands: ['move --workspace 5_send']
    match:
      - window_process: { equals: 'ms-teams' }
      - window_title: { equals: 'WhatsApp' }

  - commands: ['move --workspace 11_post']
    match:
      - window_process: { equals: 'OUTLOOK' }
      - window_process: { equals: 'olk' }
  - commands: ['set-floating', 'move --workspace 9_back']
    match:
      - window_title: { equals: 'ANT vehicle simulator' }
  - commands: ['set-floating']
    match:
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_class: { equals: 'ConsoleWindowClass' }
      - window_class: { equals: 'CASCADIA_HOSTING_WINDOW_CLASS' }

binding_modes:

keybindings:
  - commands: ['wm-cycle-focus']
    bindings: ['alt+i']

  - commands: ['wm-reload-config']
    bindings: ['alt+shift+u']

  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']
  - commands: ['set-minimized']
    bindings: ['alt+x']
  - commands: ['close']
    bindings: ['alt+q']

  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  - commands: ['focus --next-active-workspace-on-monitor']
    bindings: ['alt+oem_period']
  - commands: ['focus --prev-active-workspace-on-monitor']
    bindings: ['alt+oem_comma']

  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  - commands: ['resize --width -100']
    bindings: ['alt+_']
  - commands: ['resize --width +100']
    bindings: ['alt+oem_plus']
  - commands: ['resize --height -100']
    bindings: ['alt+shift+_']
  - commands: ['resize --height +100']
    bindings: ['alt+shift+oem_plus']

  - commands: ['focus --workspace 1_any']
    bindings: ['alt+a']
  - commands: ['focus --workspace 2_else']
    bindings: ['alt+e']
  - commands: ['focus --workspace 3_web']
    bindings: ['alt+w']
  - commands: ['focus --workspace 4_term']
    bindings: ['alt+t']
  - commands: ['focus --workspace 5_send']
    bindings: ['alt+s']
  - commands: ['focus --workspace 6_code']
    bindings: ['alt+c']
  - commands: ['focus --workspace 7_gui']
    bindings: ['alt+g']
  - commands: ['focus --workspace 8_dash']
    bindings: ['alt+d']
  - commands: ['focus --workspace 9_back']
    bindings: ['alt+b']
  - commands: ['focus --workspace 10_music']
    bindings: ['alt+m']
  - commands: ['focus --workspace 11_post']
    bindings: ['alt+p']
  - commands: ['focus --workspace 12_rest']
    bindings: ['alt+r']
  - commands: ['focus --workspace 13_fullscreen']
    bindings: ['alt+f']

  - commands: ['move --workspace 1_any', 'focus --workspace 1_any']
    bindings: ['alt+shift+a']
  - commands: ['move --workspace 2_else', 'focus --workspace 2_else']
    bindings: ['alt+shift+e']
  - commands: ['move --workspace 3_web', 'focus --workspace 3_web']
    bindings: ['alt+shift+w']
  - commands: ['move --workspace 4_term', 'focus --workspace 4_term']
    bindings: ['alt+shift+t']
  - commands: ['move --workspace 5_send', 'focus --workspace 5_send']
    bindings: ['alt+shift+s']
  - commands: ['move --workspace 6_code', 'focus --workspace 6_code']
    bindings: ['alt+shift+c']
  - commands: ['move --workspace 7_gui', 'focus --workspace 7_gui']
    bindings: ['alt+shift+g']
  - commands: ['move --workspace 8_dash', 'focus --workspace 8_dash']
    bindings: ['alt+shift+d']
  - commands: ['move --workspace 9_back', 'focus --workspace 9_back']
    bindings: ['alt+shift+b']
  - commands: ['move --workspace 10_music', 'focus --workspace 10_music']
    bindings: ['alt+shift+m']
  - commands: ['move --workspace 11_post', 'focus --workspace 11_post']
    bindings: ['alt+shift+p']
  - commands: ['move --workspace 12_rest', 'focus --workspace 12_rest']
    bindings: ['alt+shift+r']
  - commands: ['move --workspace 13_fullscreen', 'focus --workspace 13_fullscreen']
    bindings: ['alt+shift+f']

  - commands: ['focus --recent-workspace']
    bindings: ['alt+z']
  - commands: ['move --recent-workspace', 'focus --recent-workspace']
    bindings: ['alt+shift+z']
