general:
  startup_commands: ['shell-exec zebar']
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: false

gaps:
  inner_gap: '10px'

  outer_gap:
    top: '10px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  focused_window:
    border:
      # only windows 11?
      enabled: true
      color: '#ffffff'

    corner_style:
      enabled: true
      style: 'square'

  other_windows:
    border:
      enabled: true
      color: '#000000'

    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: true
      shown_on_top: false

workspaces:
  - name: "any"
    display_name: "󰋜"
  - name: "else"
    display_name: "󰥵"
  - name: "term"
    display_name: ""
  - name: "send"
    display_name: ""
  - name: "code"
    display_name: "󰨞"
  - name: "web"
    display_name: ""
  - name: "rest"
    display_name: ""
  - name: "gui"
    display_name: ""
  - name: "back"
    display_name: "󰀿"
  - name: "music"
    display_name: ""
  - name: "post"
    display_name: "󰇮"

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
  - commands: ['move --workspace music']
    match:
      - window_process: { equals: 'Spotify' }
  - commands: ['set-floating', 'move --workspace gui', 'focus --workspace gui']
    match:
      - window_process: { equals: 'ANTlab' }
      - window_title: { regex: '^(ANT lab( - C.*)?|Change User Group|Setup|Warning)$' }

binding_modes:

keybindings:
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+f']
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+u']
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']
  - commands: ['set-minimized']
    bindings: ['alt+x']
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']
  - commands: ['toggle-floating']
    bindings: ['alt+enter']
  - commands: ['set-tiling']
    bindings: ['alt+shift+enter']
  - commands: ['close']
    bindings: ['alt+q']

  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  - commands: ['resize --width -10%']
    bindings: ['alt+shift+_']
  - commands: ['resize --width +10%']
    bindings: ['alt+shift+oem_plus']

  - commands: ['focus --workspace any']
    bindings: ['alt+a']
  - commands: ['focus --workspace else']
    bindings: ['alt+e']
  - commands: ['focus --workspace term']
    bindings: ['alt+t']
  - commands: ['focus --workspace send']
    bindings: ['alt+s']
  - commands: ['focus --workspace code']
    bindings: ['alt+c']
  - commands: ['focus --workspace web']
    bindings: ['alt+w']
  - commands: ['focus --workspace rest']
    bindings: ['alt+r']
  - commands: ['focus --workspace gui']
    bindings: ['alt+g']
  - commands: ['focus --workspace back']
    bindings: ['alt+b']
  - commands: ['focus --workspace music']
    bindings: ['alt+m']
  - commands: ['focus --workspace post']
    bindings: ['alt+p']

  - commands: ['move --workspace any', 'focus --workspace any']
    bindings: ['alt+shift+a']
  - commands: ['move --workspace else', 'focus --workspace else']
    bindings: ['alt+shift+e']
  - commands: ['move --workspace term', 'focus --workspace term']
    bindings: ['alt+shift+t']
  - commands: ['move --workspace send', 'focus --workspace send']
    bindings: ['alt+shift+s']
  - commands: ['move --workspace code', 'focus --workspace code']
    bindings: ['alt+shift+c']
  - commands: ['move --workspace web', 'focus --workspace web']
    bindings: ['alt+shift+w']
  - commands: ['move --workspace rest', 'focus --workspace rest']
    bindings: ['alt+shift+r']
  - commands: ['move --workspace gui', 'focus --workspace gui']
    bindings: ['alt+shift+g']
  - commands: ['move --workspace back', 'focus --workspace back']
    bindings: ['alt+shift+b']
  - commands: ['move --workspace music', 'focus --workspace music']
    bindings: ['alt+shift+m']
  - commands: ['move --workspace post', 'focus --workspace post']
    bindings: ['alt+shift+p']

  - commands: ['focus --recent-workspace']
    bindings: ['alt+z']
  - commands: ['move --recent-workspace', 'focus --recent-workspace']
    bindings: ['alt+shift+z']
