#!/bin/bash
# ~/.use_git_exe should be a file containing the directories using git.exe
if [[ ! "$1" =~ ^(difftool|log|show)$ && -e ~/.use_git_exe ]]; then
  directories=$(< ~/.use_git_exe)
  regex=^\(${directories//$'\n'/'/.*|'}.\*\)\$
  if [[ $PWD/ =~ $regex ]]; then
    EDITOR='edit(){
      wsl.exe -e bash -c "nvim \`wslpath $1\`"
    }
    edit'
    git.exe -c core.editor="${EDITOR}" "$@"
    exit
  fi
fi
/usr/bin/git "$@"
