#!/bin/bash
# ~/.use_git_exe should be a file containing the directories using git.exe
if [[ "$1" != "difftool" && -e ~/.use_git_exe ]]; then
  directories=$(< ~/.use_git_exe)
  regex=^\(${directories//$'\n'/'/.*|'}.\*\)\$
  if [[ $PWD/ =~ $regex ]]; then
    GIT_EXE='/mnt/c/Program Files/Git/cmd/git.exe'
    EDITOR='edit(){
      wsl.exe -e bash -c "nvim \`wslpath $1\`"
    }
    edit'
    PAGER='wsl.exe -e bash -c less'
    "${GIT_EXE}" -c core.editor="${EDITOR}" -c core.pager="${PAGER}" "$@"
    exit
  fi
fi
/usr/bin/git "$@"
