#!/usr/bin/bash
function github_release() {
  local url="https://github.com/$1/releases/latest/download/$2" tmp=$(mktemp)
  wget -O ${tmp} ${url} 
  case ${2##*.} in
    "zip") unzip -o ${tmp} -d "${@:3}";;
    "gz") tar -xvzf ${tmp} -C "${@:3}";;
  esac
}

# Common packages
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y \
  curl dirmngr apt-transport-https lsb-release ca-certificates stow cmake vifm \
  zsh tmux fzf fontconfig tig qalc httpie ripgrep fd-find xsel clang nodejs jq

# Nerd Font
github_release ryanoasis/nerd-fonts Hack.zip "${HOME}/.fonts"
fc-cache -fv

# Nvim
github_release neovim/neovim nvim-linux64.tar.gz "${HOME}"
sudo ln -s "${HOME}/nvim-linux64/bin/nvim" "/usr/bin/nvim"
vim_plug="${HOME}/nvim-linux64/share/nvim/runtime/plugin"
rm "${vim_plug}"/{tar,netrw,zip}Plugin.vim
rm "${vim_plug}"/{gzip,rplugin,shada,spellfile,tohtml,tutor}.vim

# sd
sd_tag=`curl -s https://api.github.com/repos/chmln/sd/tags | jq -r '.[0].name'`
sd="sd-${sd_tag}-x86_64-unknown-linux-gnu"
github_release chmln/sd "${sd}.tar.gz" "${HOME}/bin" --strip-components=1 "${sd}/sd"

# antigen
mkdir -p "${HOME}/.antigen"
curl -L git.io/antigen > "${HOME}/.antigen/antigen.zsh"

# extract
echo '#!/usr/bin/zsh
source ~/.antigen/bundles/ohmyzsh/ohmyzsh/plugins/extract/extract.plugin.zsh
extract $1' > "${HOME}/bin/extract"
chmod +x "${HOME}/bin/extract"

# starship
starship='starship-x86_64-unknown-linux-musl.tar.gz'
github_release starship/starship ${starship} "${HOME}/bin"

if grep -q Microsoft /proc/version; then
  # win32yank
  github_release equalsraf/win32yank win32yank-x64.zip "${HOME}/bin" win32yank.exe
  chmod +x "${HOME}/bin/win32yank.exe"

  # wudo
  wsl_sudo="https://raw.githubusercontent.com/Chronial/wsl-sudo/master/wsl-sudo.py"
  wget ${wsl_sudo} -O "${HOME}/bin/wudo"
  chmod +x "${HOME}/bin/wudo"
fi
