#!zsh

if /usr/bin/git config --list | grep -q core.gitexe; then
  git.exe \
    -c core.editor='ce(){ wsl.exe -e bash -c "nvim \`wslpath $1\`"; clear; }; ce' \
    -c core.pager='cp(){ wsl.exe -e bash -c "~/bin/less"; }; cp' \
    "$@"
else
  /usr/bin/git "$@"
fi
