general:
  focus_follows_cursor: false
  cursor_follows_focus: false
  toggle_workspace_on_refocus: false
  show_floating_on_top: false
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: "false"

gaps:
  inner_gap: "7px"
  outer_gap: "3px"

focus_borders:
  active:
    enabled: true
    color: "#ffffff"
  inactive:
    enabled: false

bar:
  enabled: true
  height: "20px"
  position: "top"
  opacity: 1.0
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "12px"
  padding: "0px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"

workspaces:
  - name: "general"
  - name: "term"
  - name: "msg"
  - name: "code"
  - name: "web"
  - name: "other"
  - name: "apps"
  - name: "nook"

window_rules:
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "set floating"
    match_class_name: "#32770"
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

binding_modes:
  - name: "resize"
    keybindings:
      - command: "resize width -2%"
        binding: "H"
      - command: "resize width +2%"
        binding: "L"
      - command: "resize height +2%"
        binding: "K"
      - command: "resize height -2%"
        binding: "J"
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  - command: "focus left"
    binding: "Alt+H"
  - command: "focus right"
    binding: "Alt+L"
  - command: "focus up"
    binding: "Alt+K"
  - command: "focus down"
    binding: "Alt+J"

  - command: "move left"
    binding: "Alt+Shift+H"
  - command: "move right"
    binding: "Alt+Shift+L"
  - command: "move up"
    binding: "Alt+Shift+K"
  - command: "move down"
    binding: "Alt+Shift+J"

  - command: "binding mode resize"
    binding: "Alt+R"

  - command: "tiling direction toggle"
    binding: "Alt+V"

  - command: "focus mode toggle"
    binding: "Alt+Space"
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  - command: "toggle maximized"
    binding: "Alt+Return"
  - command: "set minimized"
    binding: "Alt+X"
  - command: "close"
    binding: "Alt+Shift+Q"
  - command: "exit wm"
    binding: "Alt+Shift+E"

  - command: "focus workspace recent"
    binding: "Alt+Z"

  - command: "reload config"
    binding: "Alt+Shift+R"

  - command: "move workspace left"
    binding: "Alt+Q"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  - command: "focus workspace term"
    binding: "Alt+T"
  - command: "focus workspace msg"
    binding: "Alt+M"
  - command: "focus workspace code"
    binding: "Alt+C"
  - command: "focus workspace web"
    binding: "Alt+W"
  - command: "focus workspace other"
    binding: "Alt+O"
  - command: "focus workspace apps"
    binding: "Alt+A"
  - command: "focus workspace nook"
    binding: "Alt+N"
  - command: "focus workspace general"
    binding: "Alt+G"

  - commands: ["move to workspace term", "focus workspace term"]
    binding: "Alt+Shift+T"
  - commands: ["move to workspace msg", "focus workspace msg"]
    binding: "Alt+Shift+M"
  - commands: ["move to workspace code", "focus workspace code"]
    binding: "Alt+Shift+C"
  - commands: ["move to workspace web", "focus workspace web"]
    binding: "Alt+Shift+W"
  - commands: ["move to workspace other", "focus workspace other"]
    binding: "Alt+Shift+O"
  - commands: ["move to workspace apps", "focus workspace apps"]
    binding: "Alt+Shift+A"
  - commands: ["move to workspace nook", "focus workspace nook"]
    binding: "Alt+Shift+N"
  - commands: ["move to workspace general", "focus workspace general"]
    binding: "Alt+Shift+G"
