general:
  startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: false
    # trigger: 'monitor_focus'

gaps:
  inner_gap: '3px'

  outer_gap:
    top: '22px'
    right: '3px'
    bottom: '3px'
    left: '3px'

window_effects:
  focused_window:
    border:
      # only windows 11?
      enabled: true
      color: '#ffffff'

  other_windows:
    border:
      enabled: true
      color: '#000000'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: false

workspaces:
  - name: "any"
    display_name: "󰋜"
  - name: "else"
    display_name: "󰥵"
  - name: "term"
    display_name: ""
  - name: "send"
    display_name: ""
  - name: "code"
    display_name: "󰨞"
  - name: "web"
    display_name: ""
  - name: "rest"
    display_name: ""
  - name: "gui"
    display_name: ""
  - name: "back"
    display_name: "󰀿"

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

binding_modes:
#   - name: 'resize'
#     keybindings:
#       - commands: ['resize --width -2%']
#         bindings: ['h', 'left']
#       - commands: ['resize --width +2%']
#         bindings: ['l', 'right']
#       - commands: ['resize --height +2%']
#         bindings: ['k', 'up']
#       - commands: ['resize --height -2%']
#         bindings: ['j', 'down']
#       - commands: ['wm-disable-binding-mode --name resize']
#         bindings: ['escape', 'enter']

  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  - commands: ['toggle-fullscreen']
    bindings: ['alt+enter']
  - commands: ['toggle-minimized']
    bindings: ['alt+x']

  # Close focused window.
  # - commands: ['close']
  #   bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  # - commands: ['wm-exit']
  #   bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+u']

  # Redraw all windows.
  # - commands: ['wm-redraw']
  #   bindings: ['alt+shift+w']

  # # Focus the next/previous workspace defined in `workspaces` config.
  # - commands: ['focus --next-workspace']
  #   bindings: ['alt+s']
  # - commands: ['focus --prev-workspace']
  #   bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+z']

  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+f']

  - commands: ['focus --workspace any']
    bindings: ['alt+a']
  - commands: ['focus --workspace else']
    bindings: ['alt+e']
  - commands: ['focus --workspace term']
    bindings: ['alt+t']
  - commands: ['focus --workspace send']
    bindings: ['alt+s']
  - commands: ['focus --workspace code']
    bindings: ['alt+c']
  - commands: ['focus --workspace web']
    bindings: ['alt+w']
  - commands: ['focus --workspace rest']
    bindings: ['alt+r']
  - commands: ['focus --workspace gui']
    bindings: ['alt+g']
  - commands: ['focus --workspace back']
    bindings: ['alt+b']

  - commands: ['move --workspace any', 'focus --workspace any']
    bindings: ['alt+shift+a']
  - commands: ['move --workspace else', 'focus --workspace else']
    bindings: ['alt+shift+e']
  - commands: ['move --workspace term', 'focus --workspace term']
    bindings: ['alt+shift+t']
  - commands: ['move --workspace send', 'focus --workspace send']
    bindings: ['alt+shift+s']
  - commands: ['move --workspace code', 'focus --workspace code']
    bindings: ['alt+shift+c']
  - commands: ['move --workspace web', 'focus --workspace web']
    bindings: ['alt+shift+w']
  - commands: ['move --workspace rest', 'focus --workspace rest']
    bindings: ['alt+shift+r']
  - commands: ['move --workspace gui', 'focus --workspace gui']
    bindings: ['alt+shift+g']
  - commands: ['move --workspace back', 'focus --workspace back']
    bindings: ['alt+shift+b']
