general:
  focus_follows_cursor: false
  cursor_follows_focus: false
  toggle_workspace_on_refocus: false
  show_floating_on_top: false
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: "false"

gaps:
  inner_gap: "10px"
  outer_gap: "5px"

focus_borders:
  active:
    enabled: true
    color: "#ffffff"
  inactive:
    enabled: false

bar:
  enabled: true
  height: "20px"
  position: "top"
  opacity: 1.0
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Hack Nerd Font Mono"
  font_size: "12px"
  padding: "0px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "clock"
      time_formatting: "HH:mm"
  components_right:
    - type: "clock"
      time_formatting: "d MMM"
      margin: "0 6px"
    - type: "clock"
      time_formatting: "Week w"
      margin: "0 6px"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      margin: "0 6px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 6px"
      padding: "0 8px"

workspaces:
  - name: "any"
  - name: "else"
  - name: "term"
  - name: "send"
  - name: "code"
  - name: "web"
  - name: "rest"

window_rules:
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "set floating"
    match_class_name: "#32770"
  - commands: ["move to workspace send", "focus workspace send"]
    match_process_name: "/msteams|Microsoft Teams|olk|(Microsoft )?Outlook/"
  - commands: ["move to workspace rest", "focus workspace rest"]
    match_title: "/Spotify|WhatsApp/"
  - commands: ["move to workspace term", "focus workspace term"]
    match_process_name: "/WindowsTerminal/"
    match_title: "Ubuntu"
  - commands: ["move to workspace code", "focus workspace code"]
    match_process_name: "/Code|PyCharm|pycharm64/"

keybindings:
  - command: "focus left"
    binding: "Alt+H"
  - command: "focus right"
    binding: "Alt+L"
  - command: "focus up"
    binding: "Alt+K"
  - command: "focus down"
    binding: "Alt+J"

  - command: "move left"
    binding: "Alt+Shift+H"
  - command: "move right"
    binding: "Alt+Shift+L"
  - command: "move up"
    binding: "Alt+Shift+K"
  - command: "move down"
    binding: "Alt+Shift+J"

  - command: "tiling direction toggle"
    binding: "Alt+V"

  - command: "focus mode toggle"
    binding: "Alt+Space"
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  - command: "toggle maximized"
    binding: "Alt+Return"
  - command: "set minimized"
    binding: "Alt+X"

  - command: "focus workspace recent"
    binding: "Alt+Z"

  - command: "reload config"
    binding: "Alt+Shift+U"

  - command: "move workspace up"
    binding: "Alt+Shift+D"
  - command: "move workspace down"
    binding: "Alt+Shift+F"

  - command: "focus workspace any"
    binding: "Alt+A"
  - command: "focus workspace else"
    binding: "Alt+E"
  - command: "focus workspace term"
    binding: "Alt+T"
  - command: "focus workspace send"
    binding: "Alt+S"
  - command: "focus workspace code"
    binding: "Alt+C"
  - command: "focus workspace web"
    binding: "Alt+W"
  - command: "focus workspace rest"
    binding: "Alt+R"

  - commands: ["move to workspace any", "focus workspace any"]
    binding: "Alt+Shift+A"
  - commands: ["move to workspace else", "focus workspace else"]
    binding: "Alt+Shift+E"
  - commands: ["move to workspace term", "focus workspace term"]
    binding: "Alt+Shift+T"
  - commands: ["move to workspace send", "focus workspace send"]
    binding: "Alt+Shift+S"
  - commands: ["move to workspace code", "focus workspace code"]
    binding: "Alt+Shift+C"
  - commands: ["move to workspace web", "focus workspace web"]
    binding: "Alt+Shift+W"
  - commands: ["move to workspace rest", "focus workspace rest"]
    binding: "Alt+Shift+R"
