watch_stylesheet: true
watch_config: true
show_systray: false
debug: true
bars:
  main-bar:
    screens: ["primary"]
    class_name: "main-bar"
    alignment:
      position: "bottom"
      align: "left"
    window_flags:
      hide_on_fullscreen: false
      hide_on_maximized: false
    dimensions:
      height: 20
    widgets:
      left: ["glazewm_workspaces"]
      right: ["group", "weather", "clock"]
    animation:
      enabled: false
  main-bar-secondary:
    screens: ["*"]
    class_name: "main-bar"
    alignment:
      position: "bottom"
      align: "left"
    window_flags:
      hide_on_fullscreen: false
      hide_on_maximized: false
    dimensions:
      height: 20
    widgets:
      left: ["glazewm_workspaces"]
    animation:
      enabled: false
widgets:
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "🔒"
      label_alt: "🔒"
      update_interval: 1
  windows:
    type: "yasb.custom.CustomWidget"
    options:
      label: "🪟"
      label_alt: ""
      class_name: "windows"
      callbacks:
        on_left: 'exec cmd /c start "" /b %USERPROFILE%\.twm\toggle-taskbar.bat'
  group:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "group"
      widgets: [
        "language",
        "bluetooth",
        "wifi",
        "control_center",
        "windows",
        "systray"
      ]
      collapse_options:
        enabled: true
        expanded_label: "📖"
        collapsed_label: "📕"
        label_position: "right"
        exclude_widgets: ["language", "bluetooth", "wifi", "control_center"]
  control_center:
    type: "yasb.control_center.ControlCenterWidget"
    options:
      label: "⚙️"
      tooltip: true
      sections_order:
        - "system_controls"
        - "quick_actions"
        - "sliders"
        - "power"
        - "media"
      popup:
        alignment: "center"
        direction: "down"
        border_color: System
        round_corners: true
        round_corners_type: normal
        offset_top: 8
      sections:
        system_controls:
          profile_image_size: 28
          power_icon: "\uE7E8"
          lock_icon: "\uE72E"
          settings_icon: "\uE713"
        quick_actions:
          show: true
          columns: 3
          label_position: "default"
          actions:
            - id: "toggle_dnd"
              label: "Do Not Disturb"
              icon: "\uf285"
            - id: "toggle_mute"
              label: "Mute"
              icon: "\ue74f"
            - id: "toggle_mic_mute"
              label: "Mic Mute"
              icon: "\uF12E"
            - id: "screenshot"
              label: "Screenshot"
              icon: "\ue91b"
            - id: "touch_keyboard"
              label: "Keyboard"
              icon: "\uE765"
            - id: "toggle_theme"
              label: "Dark Mode"
              icon: "\uE708"
        sliders:
          show: true
          brightness:
            show_slider: true
            icon: "\uE706"
            show_source_selector: true
            source_selector_icon: "\uE972"
          volume:
            show_slider: true
            icon: "\uE767"
            show_source_selector: true
            source_selector_icon: "\uE972"
          microphone:
            show_slider: true
            icon: "\uE720"
            show_source_selector: true
            source_selector_icon: "\uE972"
        media:
          show: true
          thumbnail_size: 36
          thumbnail_radius: 4
          icons:
            prev_track: "\ue622"
            next_track: "\ue623"
            play: "\uf5b0"
            pause: "\ue62e"
        power:
          show: true
          power_plan_title: "Power Plan"
          power_mode_title: "Power Mode"
          button_menu_icon: "\ue76c"
      callbacks:
        on_left: "toggle_menu"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_position: "left"
      show_battery: true
      show_unpinned_button: false
      icon_size: 14
      use_hook: true
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      enable_scroll_switching: false
      app_icons:
        enabled_populated: true
        enabled_active: true
        size: 12
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      ethernet_icon: "📶"
      wifi_icons: [
        "❌",
        "🛜",
        "🛜",
        "🛜",
        "🛜",
      ]
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span>"
      class_name: ""
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: null
      max_length_ellipsis: "..."
      tooltip: true
      icons:
        bluetooth_on: "🌱"
        bluetooth_off: "🍁"
        bluetooth_connected: "🌳"
      device_aliases: []
      keybindings: []
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        labels:
          title: "Bluetooth"
          your_devices: "Your devices"
          new_devices: "New devices"
          not_connected: "Not connected"
          connected: "Connected"
          more_settings: "More Bluetooth settings"
          connect: "Connect"
          disconnect: "Disconnect"
          connecting: "Connecting"
          disconnecting: "Disconnecting"
          pair: "Pair"
          manage: "Manage"
          power_on: "On"
          power_off: "Off"
        device_icons:
          headphones: "\ue7f6"
          headset: "\ue95b"
          speaker: "\ue7f5"
          phone: "\ue8ea"
          tablet: "\ue70a"
          laptop: "\ue7f8"
          computer: "\ue950"
          keyboard: "\ue765"
          mouse: "\ue962"
          controller: "\ue7fc"
          watch: "\ue918"
          camera: "\ue722"
          generic: "\ue702"
          battery:
            empty: "\ueba0"
            low: "\ueba2"
            medium: "\ueba5"
            high: "\ueba8"
            full: "\uebaa"
          scan: "\ue72c"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      class_name: "clock"
      label: "{📅%d/%m⌚%H:%M}"
      label_alt: "\uf017 {%d-%m-%y %H:%M:%S}"
      locale: ""
      update_interval: 1000
      timezones: []
      icons:
        clock_01 : "\udb85\udc3f"
        clock_02 : "\udb85\udc40"
        clock_03 : "\udb85\udc41"
        clock_04 : "\udb85\udc42"
        clock_05 : "\udb85\udc43"
        clock_06 : "\udb85\udc44"
        clock_07 : "\udb85\udc45"
        clock_08 : "\udb85\udc46"
        clock_09 : "\udb85\udc47"
        clock_10 : "\udb85\udc48"
        clock_11 : "\udb85\udc49"
        clock_12 : "\udb85\udc4a"
        clock_16 : "SNACK TIME !"
        clock_21 : "Zzz..."
        clock_22 : "Zzz..."
        clock_23 : "Zzz..."
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_holidays: false
        show_week_numbers: true
        show_years: true
        country_code: "AR"
        extended: false
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "next_timezone"
        on_right: "toggle_label"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      class_name: "weather"
      label: "🌡️{temp} 💧{daily_chance_of_rain}"
      label_alt: ""
      api_key: "5337407e8f054898880132623252111" # https://www.weatherapi.com/
      show_alerts: true
      tooltip: false
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "Lausanne Switzerland"
      callbacks:
        on_left: "toggle_card"
        on_right: "do_nothing"
      weather_card:
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
